name: Build, Test, and Upload Binaries

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.22]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5  # Updated to v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code
      uses: actions/checkout@v4  # Updated to v4

    - name: Get dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./... -v

    - name: Build binary
      shell: bash
      run: |
        case ${{ matrix.os }} in
          ubuntu-latest)
            GOOS=linux
            ;;
          windows-latest)
            GOOS=windows
            ;;
          macos-latest)
            GOOS=darwin
            ;;
          *)
            echo "Unsupported OS"
            exit 1
            ;;
        esac

        GOARCH=amd64
        output="build/${GOOS}_${GOARCH}/gowol"
        if [[ $GOOS == "windows" ]]; then
          output+=".exe"
        fi
        mkdir -p $(dirname $output)
        GOOS=$GOOS GOARCH=$GOARCH go build -o $output .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/build/${{ matrix.os }}_amd64/gowol
        asset_name: gowol-${{ matrix.os }}-amd64
        asset_content_type: application/octet-stream

    - name: Commit and Push Binaries to Repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git checkout -b build-binaries
        mkdir -p bin
        cp -r build/* bin/
        git add bin/
        git commit -m "Add build binaries"
        git push origin build-binaries
